// NAVIGATION
export const TOGGLE_FEATURES = "TOGGLE_FEATURES";
export const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";
export const RESET_ACTIVE_LINK = "RESET_ACTIVE_LINK";
export const RESET_FEATURES = "RESET_FEATURES";
// DASHBOARD
export const INIT_DASHBOARD = "INIT_DASHBOARD";
export const INIT_DASHBOARD_FAILED = "INIT_DASHBOARD_FAILED";
export const GET_DATABASES = "GET_DATABASES";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_DASHBOARD_LOADER = "SET_DASHBOARD_LOADER";
export const SET_DASBOARD_PRODUCTS_DATA = "SET_DASBOARD_PRODUCTS_DATA";
export const SET_DASHBOARD_SALES_DATA = "SET_DASHBOARD_SALES_DATA";

// REGISTER
export const INIT_USER_REGISTRATION = "INIT_USER_REGISTRATION";
export const REGISTER_USER_PROCESS = "REGISTER_USER_PROCESS,";
// LOGIN
export const INIT_AUTHENTICATION = "INIT_AUTHENICATION";
export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATION = "AUTHENTICATION";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";
export const RE_AUTHENTICATE = "RE_AUTHENTICATICATE";
export const CLEAR_AUTHENTICATION = "CLEAR_AUTHENTICATION";
export const LOG_OUT = "LOG_OUT";
// ADD PRODUCT
export const INIT_PRODUCT_CATEGORY = "INIT_PRODUCT_CATEGORY";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const SET_ADD_PRODUCT_LOADER = "SET_ADD_PRODUCT_LOADER";
export const REMOVE_ADD_PRODUCT_LOADER = "REMOVE_ADD_PRODUCT_LOADER";
export const GET_PRODUCT_CATEGORIES_SUCCESS = "GET_PRODUCT_CATEGORIES_SUCCESS";
export const CLEAR_ADD_PRODUCT_ERROR = "CLEAR_ADD_PRODUCT_ERROR";
export const RESET_PRODUCT_MESSENGER = "ADD_PRODUCT_MESSENGER";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const SEND_PRODUCT_MESSENGER = "SEND_PRODUCT_MESSENGER";
export const OPEN_ADD_CATEGORY = "OPEN_ADD_CATEGORY";
export const CLOSE_ADD_CATEGORY = "CLOSE_ADD_CATEGORY";
// GENERAL
export const PRODUCT_DATABASE = "PRODUCT_DATABASE";
export const SALES_DATABASE = "SALES_DATABASE";
export const PRODUCT_SALES_DATABASE = "PRODUCT_SALES_DATABASE";
export const PRODUCT_SALES_DATABASE_ERROR = "PRODUCT_SALES_DATABASE_ERROR";
export const CLEAR_PRODUCT_SALES_ERROR = "CLEAR_PRODUCT_SALES_ERROR";
export const PRODUCT_SALES_LOADER = "PRODUCT_SALES_LOADER";
export const PRODUCT_DATABASE_ERROR = "PRODUCT_DATABASE_ERROR";
export const SET_PRODUCT_DATABASE_LOADER = "SET_PRODUCT_DATABASE_LOADER";

// MESSAGE
export const MESSENGER = "MESSENGER";
export const CLEAR_MESSENGER = "CLEAR_MESSENGER";
// EDIT PRODUCT
export const SET_EDIT_LOADER = "SET_EDIT_LOADER";
export const CLEAR_EDIT_LOADER = "CLEAR_EDIT_LOADER";
export const CLEAR_PRODUCT_DATABASE_ERROR = "CLEAR_PRODUCT_DATABASE_ERROR";
export const FILTER_PRODUCTS = "FILTER PRODUCTS";
export const RESET_FILTER = " RESET_FILTER";
// PRODUCT LOG
export const SET_PRODUCT_LOG_LOADER = "SET_PRODUCT_LOG_LOADER";
export const CLEAR_PRODUCT_LOG_LOADER = "CLEAR_PRODUCT_LOG_LOADER";
export const PRODUCT_LOG_SUCCESS = "PRODUCT_LOG_SUCCESS";
export const PRODUCT_LOG_FAILED = "PRODUCT_LOG_FAILED ";
export const CLEAR_PRODUCTLOG_ERROR = "CLEAR_PRODUCTLOG_ERROR";
// DELETE
export const DELETE_PRODUCT_INIT = "DELETE_PRODUCT_INIT";
export const DELETE_PRODUCT_PROCESS = " DELETE_PRODUCT_PROCESS";
// REQUISTION
export const SET_REQUISTION_LOADER = "SET_REQUISTION_LOADER";
export const CLEAR_REQUISTION_LOADER = "CLEAR_REQUISTION_LOADER";
export const CLEAR_REQUISTION_MODAL = "CLEAR_REQUISTION_MODAL";
export const REQUISTION_MODAL = "REQUISTION_MODAL";
// VALIDATION
export const SET_VALIDATION_LOADER = "SET_VALIDATION_LOADER";
export const REMOVE_VALIDATION_LOADER = "REMOVE_VALIDATION_LOADER";
export const PATIENT_DATABASE = "PATIENT_DATABASE";
export const WARD_DATABASE = "WARD_DATABASE";
// MESSAGE
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const CLEAR_NOTIFICATION_MESSAGE = "CLEAR_NOTIFICATION_MESSAGE";
